#!/bin/bash
# SDN Path Tracing Tool - Demo Script
# Run this to start everything and test both scenarios

echo "================================================"
echo "  SDN Path Tracing Tool - Demo"
echo "================================================"
echo "  python3.10 -m venv ~/sdn-env38"
echo "  source ~/sdn-env38/bin/activate"
echo ""
echo "STEP 1: Start the Ryu controller (in a NEW terminal):"
echo "  ryu-manager controller.py --observe-links"
echo ""
echo "STEP 2: Start Mininet topology (in ANOTHER terminal, with sudo):"
echo "  sudo mn --custom topology.py --topo pathtracingtopo --controller remote --switch ovsk,protocols=OpenFlow13"
echo ""
echo "STEP 3: In Mininet CLI, run these tests:"
echo ""
echo "  --- SCENARIO 1: Allowed traffic (normal path trace) ---"
echo "  mininet> h1 ping -c 3 h4"
echo "  Expected: ping succeeds, controller logs show H1->S1->S2->S3->H4"
echo ""
echo "  mininet> h1 ping -c 3 h2"
echo "  Expected: ping succeeds, controller logs show H1->S1->H2"
echo ""
echo "  --- SCENARIO 2: Blocked traffic ---"
echo "  mininet> h2 ping -c 3 h4"
echo "  Expected: 100% packet loss (blocked by flow rule)"
echo ""
echo "  --- View flow tables ---"
echo "  mininet> sh ovs-ofctl -O OpenFlow13 dump-flows s1"
echo "  mininet> sh ovs-ofctl -O OpenFlow13 dump-flows s2"
echo "  mininet> sh ovs-ofctl -O OpenFlow13 dump-flows s3"
echo ""
echo "  --- Performance test with iperf ---"
echo "  mininet> h2 iperf -s &"
echo "  mininet> h1 iperf -c 10.0.0.2 -t 5"
echo "  Expected: TCP bandwidth report"
echo ""
echo "  --- Test all connectivity ---"
echo "  mininet> pingall"
echo ""